"""empty message

Revision ID: 434fb844e887
Revises: 00cf0197ab60
Create Date: 2020-01-24 06:01:34.198351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434fb844e887'
down_revision = '00cf0197ab60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
